# Site settings
title:       Rakh.im
email:       freetonik@gmail.com
author:      Рахим Давлеткалиев
description: "Сайт Рахима Давлеткалиева"
baseurl:     ""
url:         "http://rakh.im"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: freetonik
stackoverflow_id:
twitter_username: freetonik
google_plus_id:
linkedin_username:
angellist_username: freetonik
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none
paginate:     30
sass:
  compressed: true
